---
- name: Set PermitRootLogin yes
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin '
    insertafter: '^#PermitRootLogin '
    line: PermitRootLogin yes
  notify: Restart service sshd

- name: Set root password
  user:
    name: root
    # Ortoscale21!
    password: "{{credentials.root_password}}"
