- name: test Connection to my servers
  hosts: "{{ list_of_hosts|default('all') }}"
  remote_user: root

  tasks:
    - debug:
        var: hostvars
#        var: hosts | map('extract', hosts) | flatten | selectattr('hostname', 'defined') | list