---
- name: Synchronize two directories on one remote host.
  ansible.posix.synchronize:
    src: "{{ migration_src.synchronize_src }}"
    dest: "{{ migration_dest.mount_path }}"
    compress: no
  delegate_to: "{{ inventory_hostname }}"