---
- name: Synchronize two directories on one remote host.
#  ansible.posix.synchronize:
  synchronize:
    src: "{{ migration_src.synchronize_src }}"
    dest: "{{ migration_dest.synchronize_src }}"
#    compress: no
  delegate_to: "{{ inventory_hostname }}"